version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"

  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  pg_data: