version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "db:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    container_name: app
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - database.env
    depends_on:
      - db
volumes:
  pg_data:

